[workspace]
resolver = "2"
members = [
    "kernel",
    "boot",
    "init",
    "procmgr",
    "svcmgr",
    "shared/boot-protocol",
    "shared/elf",
    "shared/syscall",
]

[workspace.dependencies]
boot-protocol = { path = "shared/boot-protocol" }

[profile.dev]
panic = "abort"
opt-level = 1

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 2
